### ISSUE TITLE
gmt returns 0 on error

### ISSUE THREAD

**Issue by 0x1mason** [pghalliday/grunt-mocha-test#120]
This happens when a pre-test error causes the task to fail such as

```shell
[4mRunning "mochaTest:cut" (mochaTest) task[24m
Loading mock-file ....
[31m>> [39mMocha exploded!
[31m>> [39mError: Cannot find module 'uuid'[31m
>> [39m    at Function.Module._resolveFilename (module.js:336:15)[31m
>> [39m    at Module._load (module.js:278:25)[31m
...
[33mWarning: Task "mochaTest:cut" failed. Use --force to continue.[39m
```

**Comment by 0x1mason** [comment]
Nm, something else is happening.
