### ISSUE TITLE
Unable to see mocha logs in console

### ISSUE THREAD

**Issue by prolificcoder** [pghalliday/grunt-mocha-test#122]
I may be doing something wrong but I am never able to see the complete logs from mocha 
Using the plugin I see something like

```
 > RESPONSE quit()
Warning: Task "mochaTest:android" failed. Use --force to continue.
```

whereas if I run with mocha I see something like this error (happens for ES6/ES5)

```
ReferenceError: chai is not defined
      at Context._callee3$ (dist/test/android/bid-failed.js:72:13)
      at tryCatch (node_modules/babel-regenerator-runtime/runtime.js:61:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (node_modules/babel-regenerator-runtime/runtime.js:329:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (node_modules/babel-regenerator-runtime/runtime.js:94:21)
```

My grunt-mocha config looks like this

```
mochaTest: {
      reporter: 'spec',
      ui: 'bdd',
      android: {
        options: {
          reporter: 'mocha-junit-reporter',
          require: [
            'dist/helpers/setup.js'
          ]
        },
        src: ['dist/test/android/*.js']
      }
    }

```

Is there a config option that I am missing?

**Comment by pghalliday** [comment]
Grunt may be supressing the trace. Have you tried running it with `--stack`?

http://gruntjs.com/using-the-cli#stack

**Comment by pghalliday** [comment]
closing as old
