### ISSUE TITLE
Integartion with pre_commit hooks

### ISSUE THREAD

**Issue by hellboy81** [pghalliday/grunt-mocha-test#82]
`jshint` returns exit status >0 if errors are available.

Can `mocha` or `grunt-mocha-test` return error code if test failed?
At the moment  it returns always 0:

```
echo $?
0
```

Is there other ways to disallow commit code with failed tests?

**Comment by 0x1mason** [comment]
I have the same problem with what should be a non-0 exit.

```
Running "mochaTest:cut" (mochaTest) task
Loading mock-file ....
>> Mocha exploded!
>> TypeError: undefined is not a function
>>     at Object.<anonymous> (//workspace/mccp-test-pr-ci/test/unit/test_util.js:39:29)
>>     at Module._compile (module.js:460:26)
>>     at Object.Module._extensions..js (module.js:478:10)
>>     at Module.load (module.js:355:32)
>>     at Module._load (module.js:310:12)
>>     at Function.hookedLoader (/workspace/mccp-test-pr-ci/node_modules/mockery/mockery.js:128:12)
>>     at Module.require (module.js:365:17)
>>     at require (module.js:384:17)
>>     at //workspace/mccp-test-pr-ci/node_modules/mocha/lib/mocha.js:216:27
>>     at Array.forEach (native)
>>     at Mocha.loadFiles (/workspace/blah/node_modules/mocha/lib/mocha.js:213:14)
>>     at MochaWrapper.run (/workspace/mccp-test-pr-ci/node_modules/grunt-mocha-test/tasks/lib/MochaWrapper.js:51:15)
>>     at /workspace/mccp-test-pr-ci/node_modules/grunt-mocha-test/tasks/mocha-test.js:86:20
>>     at capture (//workspace/mccp-test-pr-ci/node_modules/grunt-mocha-test/tasks/mocha-test.js:33:5)
>>     at Object.<anonymous> (/workspace/mccp-test-pr-ci/node_modules/grunt-mocha-test/tasks/mocha-test.js:81:5)
>>     at Object.<anonymous> (/workspace/mccp-test-pr-ci/node_modules/grunt/lib/grunt/task.js:264:15)
Warning: Task "mochaTest:cut" failed. Use --force to continue.
```
In this case, the return code is `0`.
