### ISSUE TITLE
Mocha : newest version of mocha incompatable with grunt-mocha-test

### ISSUE THREAD

**Issue by Anthony-Mckale** [pghalliday/grunt-mocha-test#91]
think new reporter options are breaking grunt-mocha-test

https://github.com/mochajs/mocha/commit/82bba0cd9c38e9a779eba544552cee714154c6c2

causes xunit reports to break

```
Running "mochaTest:ci-test-xml" (mochaTest) task
Verifying property mochaTest.ci-test-xml exists in config...OK
Files: _test/mocha/validxml.test.js
Options: reporter="xunit", captureFile="reports/mocha_junit_results.xml", quiet=false, clearRequireCache=false
>> Mocha exploded!
>> TypeError: Cannot read property 'reporterOptions' of undefined
>>     at new XUnit (/Users/anthonymckale/IdeaProjects/digital-cms/node_modules/mocha/lib/reporters/xunit.js:39:14)
>>     at MochaWrapper.run (/Users/anthonymckale/IdeaProjects/digital-cms/node_modules/grunt-mocha-test/tasks/lib/MochaWrapper.js:56:27)
>>     at /Users/anthonymckale/IdeaProjects/digital-cms/node_modules/grunt-mocha-test/tasks/mocha-test.js:86:20
>>     at capture (/Users/anthonymckale/IdeaProjects/digital-cms/node_modules/grunt-mocha-test/tasks/mocha-test.js:33:5)
>>     at Object.<anonymous> (/Users/anthonymckale/IdeaProjects/digital-cms/node_modules/grunt-mocha-test/tasks/mocha-test.js:81:5)
>>     at Object.<anonymous> (/Users/anthonymckale/IdeaProjects/digital-cms/node_modules/grunt/lib/grunt/task.js:264:15)
>>     at Object.thisTask.fn (/Users/anthonymckale/IdeaProjects/digital-cms/node_modules/grunt/lib/grunt/task.js:82:16)
>>     at Object.<anonymous> (/Users/anthonymckale/IdeaProjects/digital-cms/node_modules/grunt/lib/util/task.js:301:30)
>>     at Task.runTaskFn (/Users/anthonymckale/IdeaProjects/digital-cms/node_modules/grunt/lib/util/task.js:251:24)
>>     at Task.<anonymous> (/Users/anthonymckale/IdeaProjects/digital-cms/node_modules/grunt/lib/util/task.js:300:12)
Warning: Task "mochaTest:ci-test-xml" failed. Use --force to continue.
Error: Task "mochaTest:ci-test-xml" failed.
    at Task.<anonymous> (/Users/anthonymckale/IdeaProjects/digital-cms/node_modules/grunt/lib/util/task.js:205:15)
    at null._onTimeout (/Users/anthonymckale/IdeaProjects/digital-cms/node_modules/grunt/lib/util/task.js:241:33)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
```

**Comment by pghalliday** [comment]
Oh no! I will take a look

**Comment by Qwerios** [comment]
I bumped into this as well and was able to get my xunit test running again by patching the mocha xunit runner itself. In mocha/lib/reporters/xunit.js I had to change line 39 from:

if (options.reporterOptions && options.reporterOptions.output) {

to

if (options && options.reporterOptions && options.reporterOptions.output) {

I think mocha should check if options are defined or not. This module could provide an empty object as a default value so everything works again I gues.

**Comment by egdelwonk** [comment]
@Qwerios / @pghalliday : Yeah, the commit above should resolve the missing reporter options and allow xunit to continue. This also allows for options to be sent to any reporter interface that can take custom options. So that's a plus. :)

**Comment by pghalliday** [comment]
cool, I'll get this released asap!

**Comment by egdelwonk** [comment]
Thanks Peter!


Cheers,


William

**Comment by pghalliday** [comment]
hmm seems to only affect the xunit reporter - working on a test case

**Comment by pghalliday** [comment]
Thanks, published now in 0.12.5 :)

**Comment by pghalliday** [comment]
Just realised that i shoud add a test for the reporterOptions themselves. Found that they didn't work as implemented. Have fixed that and released 0.12.6

**Comment by Qwerios** [comment]
I can confirm 0.12.6 works like a charm. And this is why we love open source.

Thanks!

**Comment by Anthony-Mckale** [comment]
:) cheers folks

**Comment by pghalliday** [comment]
you're welcome :)
